name: eventus
description: Eventus is a professional implementation of EventEmitter for Dart.
version: 1.0.0
author: Gil Mendes <gilmendes@designture.net>
homepage: http://designture.github.io/Eventus/
documentation:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  dict: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
